# Generated by Django 3.2.3 on 2021-11-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='equipment_images',
            new_name='images',
        ),
        migrations.AddField(
            model_name='events',
            name='images',
            field=models.ImageField(null=True, upload_to='event_images/'),
        ),
    ]
