# Generated by Django 3.2.3 on 2021-11-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_auto_20211128_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('company_detail', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='about_us/')),
                ('about_you', models.TextField(null=True)),
                ('contact_name', models.CharField(max_length=200, null=True)),
                ('contact_no', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'about_us',
            },
        ),
    ]
