# Generated by Django 3.2.3 on 2021-12-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_model',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_name',
            field=models.TextField(),
        ),
    ]
