# Generated by Django 3.2.3 on 2021-12-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_banner_image_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image_list',
            field=models.TextField(default='Nothing'),
        ),
    ]
