# Generated by Django 3.2.3 on 2021-12-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='images',
        ),
    ]
