# Generated by Django 3.2.3 on 2021-12-07 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_remove_gallery_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='gallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_app.gallery'),
            preserve_default=False,
        ),
    ]
