# Generated by Django 3.1.5 on 2022-01-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_poll', '0003_imageduplicate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageduplicate',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imageduplicate',
            name='updated_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
