# Generated by Django 3.1.5 on 2022-01-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_poll', '0004_auto_20220122_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
