# Generated by Django 3.1.5 on 2022-01-09 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_poll', '0004_auto_20220107_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image_list',
        ),
    ]
