# Generated by Django 3.1.5 on 2022-01-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_poll', '0005_remove_banner_image_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageduplicate',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
