# Generated by Django 3.1.5 on 2022-01-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_poll', '0005_auto_20220122_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='designation',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
