# Generated by Django 3.1.5 on 2022-01-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_poll', '0006_imageduplicate_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_image',
            field=models.ImageField(upload_to='ddata/blog_images/'),
        ),
    ]
