# Generated by Django 3.1.5 on 2022-01-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_poll', '0006_userrole_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='designation',
            field=models.CharField(default='User', max_length=255, null=True),
        ),
    ]
