# Generated by Django 3.1.5 on 2022-01-23 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_poll', '0007_auto_20220122_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_poll.equipment'),
        ),
    ]
