# Generated by Django 3.1.5 on 2022-01-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_poll', '0009_auto_20220111_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduser',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
