# Generated by Django 3.1.5 on 2022-01-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_poll', '0010_auto_20220111_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_pic', models.FileField(null=True, upload_to='profile_images/')),
                ('phone_no', models.IntegerField(default=0, null=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'db_table': 'Profile',
            },
        ),
    ]
