# Generated by Django 3.1.5 on 2022-01-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_poll', '0010_remove_pricelist_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventImages',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='images',
            new_name='equipement_images',
        ),
        migrations.RemoveField(
            model_name='events',
            name='images',
        ),
        migrations.RemoveField(
            model_name='package',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='package',
            name='number_of_days',
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipement_desc',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='number_of_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
