# Generated by Django 3.1.5 on 2022-01-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_poll', '0011_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='contact_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
