# Generated by Django 3.1.5 on 2022-01-24 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_poll', '0011_auto_20220124_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='equipement_images',
            new_name='equipment_images',
        ),
    ]
