# Generated by Django 3.1.5 on 2022-01-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_poll', '0013_auto_20220120_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='updated_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adduser',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adduser',
            name='updated_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='updated_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='updated_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='updated_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='updated_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='updated_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photos',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photos',
            name='updated_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='updated_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='updated_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
